    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask_app'
        static_configs:
          - targets: ['10.221.248.94:8000'] # change the address to your Flask app's address
